[metadata]
name = cfptree
version = 2.0.0
author = sfchaos
description = CFP-tree structure for efficient frequent pattern mining
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/sfchaos/cfptree
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.7